<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bridgetraces" nsURI="http://www.eclipse.org/emf/diffmerge/bridge/1.0.0/traces"
    nsPrefix="org.eclipse.emf.diffmerge.bridge.traces.gen">
  <eClassifiers xsi:type="ecore:EClass" name="Trace" eSuperTypes="#//ITrace">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolFunction" lowerBound="1"
        eType="#//ISymbolFunction" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetToCause" upperBound="-1"
        eType="#//TraceEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ITrace" instanceClassName="org.eclipse.emf.diffmerge.bridge.api.incremental.ISymbolBasedBridgeTrace$Editable"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ISymbolFunction" instanceClassName="org.eclipse.emf.diffmerge.bridge.api.ISymbolFunction"
      serializable="false"/>
</ecore:EPackage>
